server:
  port: 8084
  encoding:
    charset: UTF-8
    force: true
spring:
  cloud:
    gateway:

      routes:
        - id: user-service
          uri: lb://pubg-user-service
          predicates:
            - Path=/pubg/user/**
        - id: season-service
          uri: lb://pubg-season-data
          predicates:
            - Path=/pubg/season/**
        - id: weapon-service
          uri: lb://pubg-weapon-data
          predicates:
            - Path=/pubg/weapon/**
  application:
    name: pubg-cloud-gateway
  messages:
    encoding: UTF-8
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

jwt:
  secret: rlFgiCr2rRMch/bTWYbz=p8IY/Rj8oQdcu2zpj1/SQzrE= # ??????>=256bit???256???>=32??????????
  expiration: 259200000 # 3?????
