server:
  port: 8082
  encoding:
    charset: UTF-8
    force: true
spring:
  application:
    name: pubg-weapon-data
  messages:
    encoding: UTF-8
  datasource:
    url: jdbc:mysql://localhost:3306/my_pubg?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      db-type: mysql
jwt:
  secret: rlFgiCr2rRMch/bTWYbz=p8IY/Rj8oQdcu2zpj1/SQzrE= # 密钥，一定要>=256bit，不是256长度，>=32位长度就行，不然报错
  expiration: 259200000 # 3天过期时间
